'use strict';

var constants = {
	ADD_PROJECT        : 'ADD_PROJECT',
	DELETE_PROJECT     : 'DELETE_PROJECT',
	SELECT_PROJECT     : 'SELECT_PROJECT',
	ADD_BUG            : 'ADD_BUG',
	DELETE_BUG         : 'DELETE_BUG',
	SELECT_BUG         : 'SELECT_BUG',
	CLOSE_PROJECT      : 'CLOSE_PROJECT',
	ADD_COMMENT        : 'ADD_COMMENT',
	CLOSE_BUG          : 'CLOSE_BUG',
	CLEAR_SELECTED_BUG : 'CLEAR_SELECTED_BUG',
	SECONDS_IN_A_DAY   : 86400000,
	PRIORITY: {
		LOW    : 'Low',
		MEDIUM : 'Medium',
		HIGH   : 'High',
		SOLVED : 'Solved'
	},
	FIREBASE: {
		PROJECT_URL  : 'https://nbrs.firebaseio.com/projects',
		PASSWORD_URL : 'https://nbrs.firebaseio.com/password'
	},
	EN_LEXICON: {
		NAV_TITLE                        : 'Bug Report System',
		NOT_FOUND_TITLE                  : 'Page Not Found',
		PROJECT_LIST_TITLE               : 'Project List',
		NEW_PROJECT_BTN                  : 'New Project',
		PROJECT_CLOSED_TAG               : 'Project Closed',
		PROJECT_FORM_TITLE               : 'New Project Name',
		PROJECT_FORM_PLACEHOLDER         : 'Enter project name',
		CONFIRM                          : 'Confirm',
		CLEAR                            : 'Clear',
		BUG_LIST_TITLE                   : 'Bug List',
		NO_PROJECT_TITLE                 : 'Please select a project',
		NEW_BUG_BTN                      : 'New Bug',
		NO_BUG_INFO                      : 'There are no bugs in ',
		CLOSE_PROJECT_BTN                : 'Close Project',
		PROJECT_ALERT_TITLE              : 'Close this project?',
		PROJECT_ALERT_SUBTITLE           : 'You will not be able to edit this project anymore!',
		ALERT_CLOSE_CONFIRM              : 'Yes, close it!',
		ALERT_CLOSED_RESULT              : 'Closed!',
		ALERT_CLOSED_RESULT_SUFFIX       : ' has been closed.',
		BUG_FORM_NEW_NAME                : 'New Bug Name: ',
		BUG_FORM_NEW_NAME_PLACEHOLDER    : 'Enter bug name',
		BUG_FORM_NEW_NAME_TOOLTIP        : 'Must not be empty or contain the following characters: \'. # $ [ ] / \'',
		BUG_FORM_AUTHOR_NAME             : 'Author Name: ',
		BUG_FORM_AUTHOR_NAME_PLACEHOLDER : 'Enter your name',
		NOT_EMPTY_TOOLTIP                : 'Must not be empty',
		BUG_FORM_DESCRIPTION             : 'Description: ',
		START_DATE                       : 'Start Date: ',
		END_DATE                         : 'End Date: ',
		PRIORITY_TITLE                   : 'Priority: ',
		AUTHOR_TITLE                     : 'Author: ',
		CAUTION                          : 'Caution!',
		PASSWORD_PROMPT                  : 'Enter password to delete',
		PASSWORD_PLACEHOLDER             : 'Enter password...',
		OOPS                             : 'Oops...',
		ALERT_DELETE_RESULT              : 'Deleted',
		ALERT_DELETE_SUBTITLE            : 'The selected bug has been deleted.',
		ALERT_CLOSE_SUBTITLE             : 'project is closed!',
		ALERT_FAIL_SUBTITLE              : 'wrong password!',
		NEW_COMMENT_TITLE                : 'New Comment',
		NO_BUG_TITLE                     : 'Please select a bug',
		BUG_DETAIL_TITLE                 : 'Detail',
		BUG_COMMENT_TITLE                : 'Comments',
		NO_COMMENT_INFO                  : 'There are no comments in ',
		BUG_ALERT_TITLE                  : 'Mark this bug as solved?',
		BUG_ALERT_SUBTITLE               : 'You will not be able to edit this bug anymore!',
		BUG_CLOSE_RESULT_SUFFIX          : ' has been marked as solved.',
		TOGGLE_FORM                      : 'Open/Close Form',
		FORM_DESCRIPTION_PLACEHOLDER     : 'Enter description',
		PRIORITY_ALL                     : 'All',
		PRIORITY_LOW                     : 'Low',
		PRIORITY_MEDIUM                  : 'Medium',
		PRIORITY_HIGH                    : 'High',
		PRIORITY_SOLVED                  : 'Solved',
		PROJECT_EXIST                    : 'Same project name already exists!',
		BUG_EXIST                        : 'Same bug name already exists!'
	},
	CH_LEXICON: {
		NAV_TITLE                        : 'Bug回報系統',
		NOT_FOUND_TITLE                  : '找不到此頁面',
		PROJECT_LIST_TITLE               : '專案列表',
		NEW_PROJECT_BTN                  : '建立專案',
		PROJECT_CLOSED_TAG               : '已結案',
		PROJECT_FORM_TITLE               : '專案名稱',
		PROJECT_FORM_PLACEHOLDER         : '輸入專案名稱',
		CONFIRM                          : '確定',
		CLEAR                            : '清除',
		BUG_LIST_TITLE                   : 'Bug列表',
		NO_PROJECT_TITLE                 : '請先選擇專案',
		NEW_BUG_BTN                      : '建立Bug',
		NO_BUG_INFO                      : '目前尚無Bug在 ',
		CLOSE_PROJECT_BTN                : '結案',
		PROJECT_ALERT_TITLE              : '確定結案?',
		PROJECT_ALERT_SUBTITLE           : '結案後將無法編輯內容',
		ALERT_CLOSE_CONFIRM              : '確定',
		ALERT_CLOSED_RESULT              : '已結案！',
		ALERT_CLOSED_RESULT_SUFFIX       : ' 已結案',
		BUG_FORM_NEW_NAME                : 'Bug名稱: ',
		BUG_FORM_NEW_NAME_PLACEHOLDER    : '輸入Bug名稱',
		BUG_FORM_NEW_NAME_TOOLTIP        : '請勿留空或包含以下字元: \'. # $ [ ] / \'',
		BUG_FORM_AUTHOR_NAME             : '負責人: ',
		BUG_FORM_AUTHOR_NAME_PLACEHOLDER : '輸入姓名',
		NOT_EMPTY_TOOLTIP                : '請勿留空',
		BUG_FORM_DESCRIPTION             : '問題描述: ',
		START_DATE                       : '開始日期: ',
		END_DATE                         : '結束日期: ',
		PRIORITY_TITLE                   : '緊急程度: ',
		CAUTION                          : '注意!',
		PASSWORD_PROMPT                  : '請輸入密碼以刪除',
		PASSWORD_PLACEHOLDER             : '輸入密碼...',
		OOPS                             : '喔喔...',
		ALERT_DELETE_RESULT              : '已刪除',
		ALERT_DELETE_SUBTITLE            : '已刪除Bug',
		ALERT_CLOSE_SUBTITLE             : '已結案！',
		ALERT_FAIL_SUBTITLE              : '密碼錯誤！',
		NEW_COMMENT_TITLE                : '建立留言',
		NO_BUG_TITLE                     : '請先選擇Bug',
		BUG_DETAIL_TITLE                 : '詳細內容',
		BUG_COMMENT_TITLE                : '留言',
		NO_COMMENT_INFO                  : '目前尚無留言在 ',
		BUG_ALERT_TITLE                  : '標記此Bug為已解決',
		BUG_ALERT_SUBTITLE               : '標記為已解決後將無法編輯內容!',
		BUG_CLOSE_RESULT_SUFFIX          : ' 已標記為解決.',
		TOGGLE_FORM                      : '開啟/關閉表單',
		FORM_DESCRIPTION_PLACEHOLDER     : '輸入描述',
		PRIORITY_ALL                     : '全部',
		PRIORITY_LOW                     : '一般',
		PRIORITY_MEDIUM                  : '注意',
		PRIORITY_HIGH                    : '緊急',
		PRIORITY_SOLVED                  : '已解決',
		PROJECT_EXIST                    : '已有相同專案名稱',
		BUG_EXIST                        : '已有相同Bug名稱'
	}
};

module.exports = constants;